---
#
# Ansible managed
#
repository:
  description: Install and configure openssh on your system.
  homepage: https://robertdebock.nl/
  topics: openssh, system, security, ansible, molecule, tox, playbook
